name: driftctl

on:
  # Triggers driftctl every 10 minutes
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Run driftctl
        uses: snyk/driftctl-action@v1.3.0
        env:
          DCTL_FILTER: "Type=='aws_instance'"
        with:
          version: latest
