name: driftctl

on:
  # Triggers driftctl every 10 minutes
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: AKIA2LQ3TBZTKIS7MPMQ
      AWS_SECRET_ACCESS_KEY: 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
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - name: Run driftctl
        uses: snyk/driftctl-action@v1.3.0
        env:
          DCTL_FILTER: "Type=='aws_instance'"
        with:
          version: latest
